{% set name = "rp2biosensor" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rp2biosensor/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6b2b82021e145d531a4af6780a0f2308bf3553de1ccb8c3d0537c9229261e988

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .
  entry_points:
    - rp2biosensor = rp2biosensor.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - networkx
    - rdkit
    - rr_cache
    - rxn_rebuild

test:
  source_files:
    - tests
  imports:
    - rp2biosensor
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -m rp2biosensor --help
    - pytest -v

about:
  home: https://github.com/brsynth/rp2biosensor/
  summary: Build Sensing-Enabling Metabolic Pathways from RetroPath2.0 output
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tduigou
    - kenza12
